

server.port=8080
spring.application.name=api-gateway

# Eureka Config - Use placeholders for environment overrides
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# ROUTING LOGIC
# 1. Route for IAM Service (Auth)
spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/auth/**

# 2. Route for Game Service (WebSockets)
spring.cloud.gateway.server.webflux.routes[1].id=hotel-catalog-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://HOTEL-CATALOG-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/hotels/**

# 3. Route for User Service
spring.cloud.gateway.server.webflux.routes[2].id=booking-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://BOOKING-SERVICE
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/bookings/**


## JWT Config
jwt.secret=${JWT_SECRET:mysecretkeymysecretkeymysecretkey12}
jwt.expiration=3600

# Expose all endpoints (or specifically 'gateway')
management.endpoints.web.exposure.include=health,info,gateway
#management.endpoint.gateway.access=unrestricted